# Generated by Django 3.0.8 on 2020-08-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id_label', models.DecimalField(decimal_places=0, max_digits=32, primary_key=True, serialize=False)),
                ('numbers', models.DecimalField(decimal_places=0, max_digits=32)),
                ('province', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('county', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='reference',
            fields=[
                ('id_label', models.DecimalField(decimal_places=0, max_digits=32, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='words',
            fields=[
                ('id_label', models.DecimalField(decimal_places=0, max_digits=32, primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=32)),
                ('meaning', models.CharField(max_length=32)),
                ('pronunciation', models.CharField(max_length=100)),
                ('sample_sentence', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=32)),
                ('dialect_area', models.CharField(max_length=32)),
                ('sub_dialect_area', models.CharField(max_length=32)),
                ('dialect_field', models.CharField(max_length=32)),
                ('sub_dialect_field', models.CharField(max_length=32)),
                ('county_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01_s.location')),
                ('ref_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01_s.reference')),
            ],
        ),
    ]
