# Generated by Django 3.1.7 on 2021-03-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01_s', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='remarks',
            field=models.CharField(max_length=100),
        ),
    ]
