# Generated by Django 3.1.7 on 2021-03-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01_s', '0002_auto_20210313_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='long_and_lati',
            fields=[
                ('code', models.DecimalField(decimal_places=0, max_digits=32, primary_key=True, serialize=False)),
                ('county', models.CharField(max_length=32)),
                ('longitude', models.DecimalField(decimal_places=0, max_digits=32)),
                ('latitude', models.DecimalField(decimal_places=0, max_digits=32)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='numbers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01_s.long_and_lati'),
        ),
    ]
