# Generated by Django 3.1.7 on 2021-03-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01_s', '0003_auto_20210327_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='meaning',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='words',
            name='sample_sentence',
            field=models.CharField(max_length=100),
        ),
    ]
