# Generated by Django 3.1.7 on 2021-03-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01_s', '0004_auto_20210327_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='meaning',
            field=models.CharField(max_length=150),
        ),
    ]
