# Generated by Django 3.1.7 on 2021-03-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01_s', '0005_auto_20210327_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='long_and_lati',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=32),
        ),
        migrations.AlterField(
            model_name='long_and_lati',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=32),
        ),
    ]
