# Generated by Django 3.1.7 on 2021-03-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01_s', '0006_auto_20210328_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='long_and_lati',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='long_and_lati',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
