# Generated by Django 3.1.7 on 2021-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01_s', '0007_auto_20210328_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='long_and_lati',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='long_and_lati',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
